export { default as QuizIntro } from './QuizIntro'
export { default as PhotoQuestion } from './PhotoQuestion'
export { default as TagQuestion } from './TagQuestion'
export { default as ChoiceQuestion } from './ChoiceQuestion'
export { default as SliderQuestion } from './SliderQuestion'
export { default as MultiChoiceQuestion } from './MultiChoiceQuestion'
export { default as IconChoiceQuestion } from './IconChoiceQuestion'
export { default as PhotoQuadQuestion } from './PhotoQuadQuestion'
